; ==========================================
; DINAMIK OLARAK OLUŞTURULAN SIP TRUNK AYARLARI
; ==========================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0

; --- TRUNK: Operator_Trunk (REGISTER) ---
[Operator_Trunk-reg]
type=registration
transport=transport-udp
outbound_auth=Operator_Trunk-auth
client_uri=sip:908503607390@ikonsip.com:5060
server_uri=sip:ikonsip.com:5060
contact_user=908503607390

[Operator_Trunk-auth]
type=auth
auth_type=userpass
username=908503607390
password=gh185mcx96

[Operator_Trunk-aor]
type=aor
contact=sip:ikonsip.com:5060

[Operator_Trunk]
type=endpoint
transport=transport-udp
context=default
disallow=all
allow=ulaw,alaw,g729
aors=Operator_Trunk-aor
outbound_auth=Operator_Trunk-auth
from_user=908503607390
from_domain=ikonsip.com

[Operator_Trunk-identify]
type=identify
endpoint=Operator_Trunk
match=ikonsip.com


; ==========================================
; DINAMIK OLARAK OLUŞTURULAN KULLANICI (DAHILI) AYARLARI
; ==========================================

; --- USER: ANIL ACAR (1000) ---
[1000](webrtc_agent_template)
type=endpoint
auth=1000-auth
aors=1000
callerid=ANIL ACAR <1000>

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=6L20TFRjTm*Fo4w9

[1000]
type=aor
max_contacts=5
remove_existing=yes

; --- USER: Murat BATTAL (1001) ---
[1001](webrtc_agent_template)
type=endpoint
auth=1001-auth
aors=1001
callerid=Murat BATTAL <1001>

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=!3#DF)WXOD!FOdWa

[1001]
type=aor
max_contacts=5
remove_existing=yes

; --- USER: Cihan Köprülü (1002) ---
[1002](webrtc_agent_template)
type=endpoint
auth=1002-auth
aors=1002
callerid=Cihan Köprülü <1002>

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=Ge0zpBIP5*Ri4a!m

[1002]
type=aor
max_contacts=5
remove_existing=yes

; --- USER: MUHAMMET DOGAN (1003) ---
[1003](webrtc_agent_template)
type=endpoint
auth=1003-auth
aors=1003
callerid=MUHAMMET DOGAN <1003>

[1003-auth]
type=auth
auth_type=userpass
username=1003
password=DCztBoha)9MNu*JZ

[1003]
type=aor
max_contacts=5
remove_existing=yes

; --- USER: MUHAMMET DOGAN (1004) ---
[1004](webrtc_agent_template)
type=endpoint
auth=1004-auth
aors=1004
callerid=MUHAMMET DOGAN <1004>

[1004-auth]
type=auth
auth_type=userpass
username=1004
password=o5*O6Ila%Eu3^kOto9WRt7j0

[1004]
type=aor
max_contacts=5
remove_existing=yes
