; ==========================================
; DINAMIK OLARAK OLUŞTURULAN SIP TRUNK AYARLARI
; ==========================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
external_media_address=78.189.210.15
external_signaling_address=78.189.210.15

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0
external_media_address=78.189.210.15
external_signaling_address=78.189.210.15

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088
external_media_address=78.189.210.15
external_signaling_address=78.189.210.15

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
external_media_address=78.189.210.15
external_signaling_address=78.189.210.15

; --- OPERATOR TRUNK (OUTBOUND LINK) ---
[Operator_Trunk]
type=endpoint
context=default
disallow=all
allow=ulaw,alaw,g722,g729
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=no
media_use_received_transport=yes
outbound_auth=908503607390-auth
aors=908503607390-aor

; --- DEFAULT WEBRTC AGENT: 1000 ---
[1000]
type=endpoint
context=webrtc_agents
disallow=all
allow=ulaw,alaw,g722,g729
direct_media=no
force_rport=yes
rewrite_contact=no
rtp_symmetric=yes
webrtc=yes
use_avpf=yes
media_encryption=dtls
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
auth=1000-auth
aors=1000
callerid=Temsilci 1000 <1000>

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=1234

[1000]
type=aor
max_contacts=5
remove_existing=yes

; --- TRUNK: Operator_Trunk ---
[Operator_Trunk-auth]
type=auth
auth_type=userpass
username=908503607390
password=gh185mcx96

[Operator_Trunk-reg]
type=registration
transport=transport-udp
outbound_auth=Operator_Trunk-auth
server_uri=sip:ikonsip.com:5060
client_uri=sip:908503607390@ikonsip.com:5060
retry_interval=60

[Operator_Trunk-aor]
type=aor
contact=sip:ikonsip.com:5060

[Operator_Trunk]
type=endpoint
transport=transport-udp
context=from-trunk
disallow=all
allow=ulaw,alaw,g722,g729
aors=Operator_Trunk-aor
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
outbound_auth=Operator_Trunk-auth
from_user=908503607390
from_domain=ikonsip.com

[Operator_Trunk-identify]
type=identify
endpoint=Operator_Trunk
match=ikonsip.com


; ==========================================
; DINAMIK OLARAK OLUŞTURULAN KULLANICI (DAHILI) AYARLARI
; ==========================================

; --- USER: Murat BATTAL (1001) ---
[1001]
type=endpoint
context=webrtc_agents
disallow=all
allow=ulaw,alaw,g722,g729
direct_media=no
force_rport=yes
rewrite_contact=no
rtp_symmetric=yes
webrtc=yes
use_avpf=yes
media_encryption=dtls
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
auth=1001-auth
aors=1001
callerid=Murat BATTAL <1001>

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=!3#DF)WXOD!FOdWa

[1001]
type=aor
max_contacts=5
remove_existing=yes

; --- USER: Cihan Köprülü (1002) ---
[1002]
type=endpoint
context=webrtc_agents
disallow=all
allow=ulaw,alaw,g722,g729
direct_media=no
force_rport=yes
rewrite_contact=no
rtp_symmetric=yes
webrtc=yes
use_avpf=yes
media_encryption=dtls
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
auth=1002-auth
aors=1002
callerid=Cihan Köprülü <1002>

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=Ge0zpBIP5*Ri4a!m

[1002]
type=aor
max_contacts=5
remove_existing=yes
