; ==========================================
; PJSIP WebRTC Transport & Endpoint Ayarlari
; ==========================================

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
external_signaling_address=127.0.0.1:8089


; WebRTC Temsilci Şablonu
[webrtc_agent_template](!)
type=endpoint
webrtc=yes
context=webrtc_agents
transport=transport-wss
media_address=127.0.0.1
disallow=all
allow=ulaw,alaw,g722
dtls_verify=fingerprint
dtls_cert_file=/etc/asterisk/keys/asterisk.pem
dtls_private_key=/etc/asterisk/keys/asterisk.pem
dtls_setup=actpass
media_encryption=dtls
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
ice_support=yes
use_avpf=yes
media_use_received_transport=yes

; Temsilci 200 (Dahili numara)
[200](webrtc_agent_template)
type=endpoint
auth=200-auth
aors=200

[200-auth]
type=auth
auth_type=userpass
username=200
password=temsilci_sifre_321

[200]
type=aor
max_contacts=5
remove_existing=yes

#include pjsip_custom.conf
