; ==========================================
; DINAMIK OLARAK OLUŞTURULAN KUYRUK AYARLARI
; ==========================================

[test]
strategy=ringall
timeout=15
retry=5
wrapuptime=0
autopause=no
maxlen=0
joinempty=yes
leavewhenempty=no
member => PJSIP/1000

[test 2 ]
strategy=ringall
timeout=15
retry=5
wrapuptime=0
autopause=no
maxlen=0
joinempty=yes
leavewhenempty=no
