; ==========================================
; DINAMIK OLARAK OLUŞTURULAN KUYRUK AYARLARI
; ==========================================

[2000]
strategy=random
timeout=15
retry=5
wrapuptime=0
autopause=no
maxlen=0
joinempty=yes
leavewhenempty=no
member => PJSIP/1000
